# @generated by `cargo run --bin gen_stub`; DO NOT EDIT BY HAND.
#
# Source of truth: the Query / Command / Register catalogs in the sismatic
# crate (src/protocol/instructions/). Regenerate after changing them and commit
# the result; `cargo test` fails if this file drifts.
#
# Name arguments are case-insensitive and treat '-' and '_' as equivalent, so
# e.g. "SSH_PORT", "ssh-port" and "ssh_port" are all accepted at runtime.
# The unions below list every accepted spelling in lowercase form.

from typing import Literal

QueryName = Literal[
    "firmware",
    "running_state",
    "unit_name",
    "telnet_port",
    "ssh_port",
    "http_port",
    "snmp_port",
    "https_port",
    "snmp_unit_location",
    "snmp_unit_contact",
    "snmp_private_community_string",
    "snmp_public_community_string",
    "snmp_state",
    "dhcp_mode",
    "timezone",
    "mac_address",
    "port_timeout",
    "global_port_timeout",
    "model_name",
    "model_description",
    "active_alarms",
    "part_number",
    "contributor",
    "course",
    "coverage",
    "date",
    "description",
    "format",
    "identifier",
    "presenter",
    "relation",
    "rights",
    "source",
    "subject",
    "systemname",
    "title",
    "type",
]

CommandName = Literal[
    "startrecording",
    "start",
    "stoprecording",
    "stop",
    "pauserecording",
    "pause",
]

RegisterName = Literal[
    "contributor",
    "course",
    "coverage",
    "description",
    "format",
    "language",
    "presenter",
    "publisher",
    "relation",
    "rights",
    "source",
    "subject",
    "systemname",
    "title",
    "type",
]

class Alarm:
    """One active alarm reported by a device."""

    @property
    def name(self) -> str: ...
    @property
    def level(self) -> str: ...

class Sis:
    """A pool of Extron devices, addressable from Python by id."""

    @staticmethod
    def from_toml(path: str) -> "Sis":
        """Deprecated alias for `from_file`, kept for backwards compatibility."""
        ...

    @staticmethod
    def from_file(path: str) -> "Sis":
        """Build a session from a config file (`.toml`, `.json`, `.yaml`/`.yml`), opening no connections yet."""
        ...

    @staticmethod
    def from_config(config: dict) -> "Sis":
        """Build a session from a pre-parsed mapping (defaults table + device list), opening no connections yet."""
        ...

    def ids(self) -> list[str]:
        """The ids of every configured device."""
        ...

    def query(self, device: str, name: QueryName) -> int | bool | str | list[Alarm]:
        """Read a built-in field (e.g. \"firmware\", \"ssh_port\") from a device."""
        ...

    def command(self, device: str, name: CommandName) -> str:
        """Run a recorder command (e.g. \"start\", \"stop\") on a device."""
        ...

    def register(self, device: str, name: RegisterName, value: str) -> str:
        """Write `value` into a metadata register (e.g. \"title\") on a device."""
        ...

    def close(self) -> None:
        """Close all SSH connections and shut the session down. Idempotent."""
        ...

    def __enter__(self) -> "Sis": ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...
