[defaults]
username = "joe"
password = "schmoe"
eager = true
sis_keepalive_secs = 120

[[device]]
id = "Hall A"
host = "10.0.150.1"

[[device]]
id = "Hall B"
host = "10.0.150.2"

[[device]]
id = "Atrium"
host = "10.0.150.3"
