//! Generator for the Python type stub (`sismatic/__init__.pyi`).
//!
//! The stub is the consumer-facing documentation of which strings are valid
//! arguments to [`Sis.query`], [`Sis.command`], and [`Sis.register`]. It is
//! derived entirely from the instruction catalogs, so it can never disagree
//! with what the parser actually accepts. [`generate`] renders the file;
//! `cargo run --bin gen_stub` writes it, and a test in this module fails if the
//! committed copy drifts.
//!
//! [`Sis.query`]: crate::stub
//! [`Sis.command`]: crate::stub
//! [`Sis.register`]: crate::stub

use crate::protocol::instructions::commands::Command;
use crate::protocol::instructions::query::Query;
use crate::protocol::instructions::register::Register;

const HEADER: &str = "\
# @generated by `cargo run --bin gen_stub`; DO NOT EDIT BY HAND.
#
# Source of truth: the Query / Command / Register catalogs in the sismatic
# crate (src/protocol/instructions/). Regenerate after changing them and commit
# the result; `cargo test` fails if this file drifts.
#
# Name arguments are case-insensitive and treat '-' and '_' as equivalent, so
# e.g. \"SSH_PORT\", \"ssh-port\" and \"ssh_port\" are all accepted at runtime.
# The unions below list every accepted spelling in lowercase form.

from typing import Literal

";

/// Render the full `sismatic/__init__.pyi` type stub.
pub fn generate() -> String {
    let mut out = String::from(HEADER);

    out.push_str(&literal_alias(
        "QueryName",
        Query::ALL.iter().flat_map(|q| q.accepted()),
    ));
    out.push('\n');
    out.push_str(&literal_alias(
        "CommandName",
        Command::ALL.iter().flat_map(|c| c.accepted()),
    ));
    out.push('\n');
    out.push_str(&literal_alias(
        "RegisterName",
        Register::ALL.iter().flat_map(|r| r.accepted()),
    ));
    out.push('\n');
    out.push_str(CLASS);
    out
}

/// A `Name = Literal["a", "b", ...]` alias, one accepted spelling per line,
/// lowercased so the members match the idiomatic Python call style.
fn literal_alias<'a>(name: &str, values: impl Iterator<Item = &'a &'a str>) -> String {
    let mut block = format!("{name} = Literal[\n");
    for value in values {
        block.push_str(&format!("    \"{}\",\n", value.to_ascii_lowercase()));
    }
    block.push_str("]\n");
    block
}

/// The `Sis` class surface. Fixed shape (only the `Literal` unions above change
/// with the catalog), so it is a constant rather than generated.
const CLASS: &str = "\
class Sis:
    \"\"\"A pool of Extron devices, addressable from Python by id.\"\"\"

    @staticmethod
    def from_toml(path: str) -> \"Sis\":
        \"\"\"Build a session from a `devices.toml`, opening no connections yet.\"\"\"
        ...

    def ids(self) -> list[str]:
        \"\"\"The ids of every configured device.\"\"\"
        ...

    def query(self, device: str, name: QueryName) -> int | bool | str:
        \"\"\"Read a built-in field (e.g. \\\"firmware\\\", \\\"ssh_port\\\") from a device.\"\"\"
        ...

    def command(self, device: str, name: CommandName) -> str:
        \"\"\"Run a recorder command (e.g. \\\"start\\\", \\\"stop\\\") on a device.\"\"\"
        ...

    def register(self, device: str, name: RegisterName, value: str) -> str:
        \"\"\"Write `value` into a metadata register (e.g. \\\"title\\\") on a device.\"\"\"
        ...
";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stub_matches_committed_file() {
        let committed = include_str!("../python/sismatic/__init__.pyi");
        assert_eq!(
            generate(),
            committed,
            "python/sismatic/__init__.pyi is stale — regenerate with `cargo run --bin gen_stub` and commit the result"
        );
    }
}
